name: Upload virtualenv.pyz to release

on:
  release:
    types: [published]

# Sets the permissions for GITHUB_TOKEN to allow writing to releases
permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Upload virtualenv.pyz to release
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "${{ github.event.release.assets_url }}?name=virtualenv.pyz&label=" \
            --data-binary "@public/virtualenv.pyz"

